{{- if and (.Values.auth.enabled) (not .Values.auth.existingKeySecret) -}}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "mongodb-sharded.name" . }}
    chart: {{ template "mongodb-sharded.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 4 }}
{{- end }}
  name: {{ template "mongodb-sharded.keySecret" . }}
type: Opaque
data:
  key.txt: {{ .Values.auth.key | b64enc }}
{{- end -}}